AI ML 
ASSIGNMENT NO. 14

Name - Sumit Goregaonkar 
College - Manav school of polytechnic, Akola 
Domain - AI ML DEVELOPMENT

Q1. (Basic Array Creation)
Write a program to:
a) Create a 1D array with elements [10, 20, 30, 40, 50] using np.array().
b) Create a 2D array (3x3) using np.array().
Print both arrays along with their shape and data type (dtype).

In [2]:
# A)
import numpy as np

arr = np.array ([10, 20, 30, 40, 50])
print(arr)

# B)
import numpy as np
arr = np.array([
    [1, 2, 3], 
    [4, 5, 6], 
    [7, 8, 9]])
print(arr)

[10 20 30 40 50]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Q2. (np.zeros() and np.ones())
Create the following using NumPy:
a) A 1D array of 8 zeros.
b) A 2D array of shape (4, 4) filled with ones.
c) A 3x3 matrix of zeros.
Print all arrays with proper labels.

In [5]:
# A)
import numpy as np

arr = np.zeros(8)
print(arr)

# B)
import numpy as np

arr = np.ones((4, 4))
print(arr)

# C)
import numpy as np

arr = np.ones((3, 3, 3))
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


Q3. (np.arange())
Use np.arange() to create and print the following arrays:
a) Numbers from 0 to 20 (step 1).
b) Even numbers from 10 to 50.
c) Numbers from 5 to 100 with step of 5.

In [ ]:
# A)
import numpy as np

arr = np.arange(10)
print(arr)

# B)
import numpy as np

arr = np.arange(10, 51, 2)
print(arr)

# C)
import numpy as np

arr = np.arange(10, 101, 5)
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]
[ 10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90  95
 100]


Q4. (np.linspace())
Use np.linspace() to create:
a) 10 equally spaced numbers between 0 and 5.
b) 15 equally spaced numbers between -10 and 10.
Print the arrays and their length.

In [9]:
# A)
import numpy as np

arr = np.linspace(0, 5, 10)
print(arr)

# B)
import numpy as np

arr = np.linspace(-10, 10, 15)
print(arr)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
[-10.          -8.57142857  -7.14285714  -5.71428571  -4.28571429
  -2.85714286  -1.42857143   0.           1.42857143   2.85714286
   4.28571429   5.71428571   7.14285714   8.57142857  10.        ]


Q5. (Random Arrays)
Write a program to generate:
a) A 1D array of 10 random numbers between 0 and 1 using np.random.rand().
b) A 3x3 matrix of random numbers from standard normal distribution using
np.random.randn().
c) A 2D array (4x5) of random integers between 10 and 50 using
np.random.randint().
Print all with proper headings.

In [13]:
# A)
import numpy as np

arr = np.random.rand(10)
print(arr)

# B)
import numpy as np

arr = np.random.rand(3, 3)
print(arr)

# C)
import numpy as np

arr = np.random.rand(10, 50, 4, 5)
print(arr)




[0.42964117 0.00797768 0.53712103 0.25183019 0.73056069 0.52997051
 0.95755803 0.54981019 0.10536409 0.09554274]
[[0.8274675  0.79674977 0.93097681]
 [0.49668255 0.34359504 0.97583211]
 [0.36173095 0.87200131 0.73932949]]
[[[[1.13349393e-02 7.90342267e-01 4.20728732e-01 9.79440466e-01
    6.73095000e-01]
   [3.12634438e-01 6.66989467e-01 3.61851656e-01 7.62074513e-01
    7.52732301e-01]
   [9.00324787e-02 5.47439736e-01 9.15917849e-01 9.62030003e-01
    6.45384996e-01]
   [7.67918458e-01 6.05868260e-03 3.54035732e-01 5.84208583e-01
    2.20810668e-01]]

  [[7.67224719e-01 2.38923611e-01 5.35821467e-01 4.97525682e-01
    8.44842960e-02]
   [6.21830942e-01 4.16129306e-01 2.72622038e-01 8.92774809e-01
    3.86486699e-04]
   [4.84602434e-01 4.26231919e-01 5.06848742e-01 9.47875321e-01
    4.78685841e-01]
   [7.33605035e-01 7.99196060e-01 1.68200718e-01 7.87542602e-01
    9.19347074e-01]]

  [[6.29492276e-01 8.81764663e-01 8.61191645e-01 6.61837374e-01
    1.96235663e-01]
   [2.60134791e-01

Q6. (Vectors and Basic Operations)
Create two vectors:
v1 = np.array([2, 4, 6, 8])
v2 = np.array([1, 3, 5, 7])
Perform and print:
Addition
Subtraction
Element-wise multiplication
Dot product

In [14]:
import numpy as np

v1 = np.array([2, 4, 6, 8])
v2 = np.array([1, 3, 5, 7])

print(v1 + v2)  # Addition
print(v1 - v2)  # Subtraction
print(v1 * v2)  # Multiplication
print(v1 / v2)  # Division


[ 3  7 11 15]
[1 1 1 1]
[ 2 12 30 56]
[2.         1.33333333 1.2        1.14285714]


Q7. (Matrices and Operations)
Create two 3x3 matrices:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[9,8,7],[6,5,4],[3,2,1]])
Perform the following:
Matrix addition
Matrix multiplication (@ or np.dot())
Element-wise multiplication (*)
Print the results clearly.

In [15]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

print(A + B)  # Addition
print(A - B)  # Subtraction
print(A * B)  # Multiplication
print(A / B)  # Division

[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]
[[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]


Q8. (Properties of Arrays)
Create a 4x4 matrix of random integers between 1 and 100.
Print:
Shape
Dimension (ndim)
Total number of elements (size)
Data type
min and max values

In [16]:
import numpy as np

mat = np.random.randint(1, 100, (4, 4))

print(mat)

[[91 14 46 69]
 [ 1 11 30 89]
 [34 90 40 17]
 [ 9 92 20 93]]


Q9. (Combined - Random + Reshape + Statistics)
Generate a 1D array of 20 random integers between 1 and 50 using
np.random.randint().
Reshape it into a 4x5 matrix.
Print the sum, mean, and standard deviation of the matrix.
Find the maximum value in each row.

In [18]:
import numpy as np

# Generate 20 random integers between 1 and 50
arr = np.random.randint(1, 51, 20)

print("Original 1D Array:")
print(arr)

# Reshape into 4x5 matrix
matrix = arr.reshape(4, 5)

print("\n4x5 Matrix:")
print(matrix)

print("\nSum =", np.sum(matrix))
print("Mean =", np.mean(matrix))
print("Standard Deviation =", np.std(matrix))

print("\nMaximum value in each row:")
print(np.max(matrix, axis=1))

Original 1D Array:
[23 13 15 26 15  5  4 36 43 24 11 19 10 42  3 28 43  4 40 36]

4x5 Matrix:
[[23 13 15 26 15]
 [ 5  4 36 43 24]
 [11 19 10 42  3]
 [28 43  4 40 36]]

Sum = 440
Mean = 22.0
Standard Deviation = 13.794926603646719

Maximum value in each row:
[26 43 42 43]


Q10. (Mini Project - NumPy Application)
Create a Simple Statistics Calculator using NumPy:
Write a program that:
Asks the user how many numbers they want to generate.
Generates that many random numbers between 10 and 100 using
np.random.randint().
Stores them in a 1D array.
Prints:
The array
Mean, Median, Standard Deviation
Minimum and Maximum
Reshapes into a 2D array (if possible) and prints row-wise sum.
Use proper comments and exception handling where needed.

In [19]:
import numpy as np

try:
    n = int(input("How many numbers do you want to generate? "))

    if n <= 0:
        print("Please enter a positive number.")

    else:
        arr = np.random.randint(10, 101, n)

        print("\nGenerated Array:")
        print(arr)


        print("\nStatistics")
        print("Mean =", np.mean(arr))
        print("Median =", np.median(arr))
        print("Standard Deviation =", np.std(arr))
        print("Minimum =", np.min(arr))
        print("Maximum =", np.max(arr))

        rows = int(np.sqrt(n))

        while rows > 1:
            if n % rows == 0:
                cols = n // rows

                matrix = arr.reshape(rows, cols)

                print("\nReshaped 2D Array:")
                print(matrix)

                print("\nRow-wise Sum:")
                print(np.sum(matrix, axis=1))
                break

            rows -= 1
        else:
            print("\nReshaping into a 2D array is not possible.")

except ValueError:
    print("Invalid input! Please enter an integer.")
except Exception as e:
    print("Error:", e)


Generated Array:
[15 75 78 60 88 97 58 47 74 95]

Statistics
Mean = 68.7
Median = 74.5
Standard Deviation = 23.58834457947399
Minimum = 15
Maximum = 97

Reshaped 2D Array:
[[15 75 78 60 88]
 [97 58 47 74 95]]

Row-wise Sum:
[316 371]
